from random import choice
from time import sleep
alunos = input('Digite o nome dos alunos, separando-os por vírgula: ').split(', ')
escolhido = choice(alunos)
print('O aluno escolhido foi...')
sleep(5)
print('.')
sleep(3)
print('.')
sleep(3)
print('.')
sleep(3)
print('Aguarde! Selecionando o melhor aluno para tal ação.')
sleep(5)
print('Mais um pouco...')
sleep(3)
print('Quase lá...')
sleep(2)
print('E o aluno foi...')
sleep(0.5)
print('...')
sleep(6)
print(f'{escolhido.upper()}!!!!!')
