input = input('Digite seu nome completo: ')
nome = input.strip()
print(f'Nome em letras maiúsculas -> {nome.upper()}')
print(f'Nome em letras minúsculas -> {nome.lower()}')
print(f'Quantidade de letras no nome completo -> {len(nome.replace(' ', ''))}')
print(f'Quantidade de letras no primeiro nome -> {nome.find(' ')}')